### ISSUE TITLE
Feature Request: Enhanced clipboard Ops

### ISSUE THREAD

**Issue by Zetaphor** [cables-gl/cables_electron#100]
Once #99 is solved it would be nice to have an the following clipboard related OPs

* Read text from the clipboard
* Read images from the clipboard
* Write images to the clipboard

I'd be happy to implement this once the native API support is enabled for standalone. It should be possible to implement this in the web version today.

The current CopyToClipboard op only supports the writeText method.

https://developer.mozilla.org/en-US/docs/Web/API/Clipboard

**Comment by steam0r** [comment]
related issue is solved, you want to tackle this? happy to hear/give some feedback! maybe these could check for permission and be the same ops as on the web...so if you run chrome in non-sandboxed mode that might work as well.

**Comment by steam0r** [comment]
this has been idle for a while, i'll close this for now
