### ISSUE TITLE
Poor contrast in the code editor Find dialog

### ISSUE THREAD

**Issue by Zetaphor** [cables-gl/cables_electron#101]
## Environment

Running 0.0.5 AppImage on NixOS 24.05-stable with KDE Wayland using the Breeze Dark theme with a dark GTK theme

## Description

The UI for the find/replace dialog is extremely difficult to read:

![image](https://github.com/cables-gl/cables_electron/assets/3112763/1734333a-c075-421e-945d-12635708a1da)

![image](https://github.com/cables-gl/cables_electron/assets/3112763/9d7e9344-19a0-4b07-bf62-ee6082bbccb8)

**Comment by steam0r** [comment]
how did you get this? what is this? :)

**Comment by Zetaphor** [comment]
Open the code for an op inside the application, press CTRL-F
