### ISSUE TITLE
Explicitly declare ECMAScript version

### ISSUE THREAD

**Issue by Zetaphor** [cables-gl/cables_electron#102]
I'm using `async/await` and I'm seeing this warning:

![image](https://github.com/cables-gl/cables_electron/assets/3112763/b375388c-4440-4681-a23b-a25d94ef68d4)

I'm not sure what Electron defaults to, but it would ideal to explicitly enable support for ES2017 language features if possible. This feature is working currently, it's just a warning.

**Comment by steam0r** [comment]
this is "fixed" on dev.cables.gl and will be in the next standalone release
