### ISSUE TITLE
Unable to load extension ops

### ISSUE THREAD

**Issue by Zetaphor** [cables-gl/cables_electron#103]
## Environment

Running 0.0.5 AppImage on NixOS 24.05-stable with KDE Wayland

## Reproduction Steps

1. Create a new patch
2. Using the command palette load an Op extension (ie: Voice)

![image](https://github.com/cables-gl/cables_electron/assets/3112763/ed8b7108-63a7-4292-9396-80743e24ac66)

This is possibly related to #9

**Comment by steam0r** [comment]
works in 0.0.9

**Comment by Zetaphor** [comment]
Confirmed fixed in v0.0.9
