### ISSUE TITLE
External Op file not created

### ISSUE THREAD

**Issue by Zetaphor** [cables-gl/cables_electron#104]
## Environment

Running 0.0.5 AppImage on NixOS 24.05-stable with KDE Wayland

## Description

I'm not sure how to reproduce this as my reproduction test just failed.

When I created the SearXNG Image Search op and patch, the op was embedded into the `.cables` file rather than being in `ops/base/Ops.Standalone.SearxImageSearch.js`. The op in [that cables file](https://github.com/Zetaphor/cables-patches-ops/blob/main/content/searx-image-search/searx-image-search-Example.cables) does appear under the `Ops.Standalone` namespace.

![image](https://github.com/cables-gl/cables_electron/assets/3112763/ebfe586a-b483-4234-b1ae-7ee543ee43f6)

I initially assumed this was because this op didn't use `op.require` but a new default op in a new patch creates the external file as expected :thinking:

**Comment by steam0r** [comment]
not sure i understand the problem here, that cables-file looks fine and your search screenshot does too, doesnt it?

**Comment by Zetaphor** [comment]
Maybe I'm misunderstanding something.

Normally when I create these example patches and create a custom op, that op is saved as an external file in ops/base/exampleop.js/exampleop.json

However for some reason in the case of this one specific patch with this one op, the op file was instead embedded into the `.cables` patch file instead of being stored separately as its own `.js` and .json` file.

I've been unable to reproduce this, as every future custom op I've created has been saved to an external file.

**Comment by steam0r** [comment]
hm, that .cables file you uploaded is fine, it has no "op inside". that file stores the settings of your ops in your project, placement, links, parameters, youname it.  maybe you created the op in another directory:

![Bildschirmfoto 2024-06-12 um 17 17 15](https://github.com/cables-gl/cables_electron/assets/151271/7a385e95-a2b5-4ffc-95f0-3f5d3bb785de)

the lower options (basically your "user dir") is the default option for when you didnt save your patch yet. we are not sure yet, it at least needs some indicator or move/copy jobs. i bet you will find your op there :)

![Bildschirmfoto 2024-06-12 um 17 19 50](https://github.com/cables-gl/cables_electron/assets/151271/72ff0345-fe05-4f07-aefe-eddfd2c7ab63)

this rightmost icon (which we will move to the op editor buttons in next release) will open the directory the op is located in.

**Comment by Zetaphor** [comment]
Yep, that was it, it was stored in the alternative directory in my `.config` folder
