### ISSUE TITLE
Electron Camera permission not enabled

### ISSUE THREAD

**Issue by Zetaphor** [cables-gl/cables_electron#105]
## Environment

Running 0.0.5 AppImage on NixOS 24.05-stable with KDE Wayland

## Reproduction steps:

1. Create a new patch, add a WebcamTexture node connected to a MainLoop
2. Save the patch and reload

![image](https://github.com/cables-gl/cables_electron/assets/3112763/b5a3963c-956e-4692-9371-c2f550a73eb0)

**Comment by steam0r** [comment]
cant reproduce this in 0.0.8 anymore, is this still the case?

**Comment by 60-hz** [comment]
Duplicate of https://github.com/cables-gl/cables_electron/issues/88
Works with 0.0.8 under MacOS 14.13.1

**Comment by Zetaphor** [comment]
Confirmed on Linux AppImage as well
