### ISSUE TITLE
Welcome Menu can be closed

### ISSUE THREAD

**Issue by 60-hz** [cables-gl/cables_electron#112]
**Describe the bug**
Closing "Welcome" menu on left side bar doesn't allows to reach it anymore inside the same session.
No "New Patch" button anymore, need to relaunch.

**How To Reproduce**
1. Clic on the Left Arrow to open Welcome Menu
2. Clic on the cross to close Welcome menu
3. Cannot open this menu again (No more Arrow to open)

**Platform**
- MacOS 14.3.1

**Before** 
<img width="297" alt="Capture d’écran 2024-06-12 à 21 15 40" src="https://github.com/cables-gl/cables_electron/assets/5449719/eff6eebc-f500-42c4-8d0c-12c06f0a8bc4">

**Menu open**
<img width="654" alt="Capture d’écran 2024-06-12 à 21 15 54" src="https://github.com/cables-gl/cables_electron/assets/5449719/4e7eb7ff-27cb-4a1c-8b5f-1226ed8ab1e6">

**After Closing**
<img width="283" alt="Capture d’écran 2024-06-12 à 21 36 20" src="https://github.com/cables-gl/cables_electron/assets/5449719/3e5c1bde-86ef-49cd-a7d1-5d3ad57ca97d">

**Comment by steam0r** [comment]
"new patch" moved here:

![Bildschirmfoto 2024-06-12 um 15 46 32](https://github.com/cables-gl/cables_electron/assets/151271/c08a03ae-05d8-4319-970f-a9cc6663c68d)

and also here is (still) available here:

![Bildschirmfoto 2024-06-12 um 15 47 47](https://github.com/cables-gl/cables_electron/assets/151271/70a2681d-2f38-4b7d-96ad-345a024912c7)

if you need the welcome screen back cmd-p "welcome" is there for you:

![Bildschirmfoto 2024-06-12 um 15 46 42](https://github.com/cables-gl/cables_electron/assets/151271/e82662ea-6f1f-4e06-bb66-39daaece32cb)

**Comment by steam0r** [comment]
will keep this open as i want this linked elsewhere
