### ISSUE TITLE
Set Time doesn't work with VideoTexture Op

### ISSUE THREAD

**Issue by 60-hz** [cables-gl/cables_electron#123]
**Describe the bug**
When changing the "Set Time" value, the video is stuck to first frame only.
Same patch and video works well in cables.gl web

**How To Reproduce**
1. Open Editor
2. Load a video
3. Change Set Time

**Platform**
- MacOS 14.3.1
- Cables-0.1.1

**Comment by steam0r** [comment]
adding this as a reference, as it seems to be a bug/problem in electron/chromium:

https://github.com/cypress-io/cypress/issues/7150
