### ISSUE TITLE
AssetPathURL produce invalid urls

### ISSUE THREAD

**Issue by kikohs** [cables-gl/cables_electron#135]
My projects is: 

`C:\Users\kirel\Documents\Cables\projects\project.cables`
There is an `assets` folder next to it.

This is what the AssetPathURL returns
`C:\Users\kirel\Documents\Cables\projects//assets/66b33f767923143b8c44516c/test`

**Comment by steam0r** [comment]
lovely :) how did you add that asset?

**Comment by kikohs** [comment]
I'm using the OP, AssetPathURl. There is no asset yet, I want to get the default path to save an image from the web to disk.

**Comment by steam0r** [comment]
ah assetpathurl...will check on that, thanks
