### ISSUE TITLE
issue with subpatch / subops in standalone 0.2.0

### ISSUE THREAD

**Issue by nippotam** [cables-gl/cables_electron#138]
I create as subops in cables 0.2 on my Mac and impossible to create input and outputs (cf https://www.youtube.com/watch?v=wmy5jAzeRt8)

**Describe the bug**
No input and output on the subpatch

**How To Reproduce**
1. select ops
2. Click on create ops button
3. (it creates a Subpatch2Template)
4. click on the Subpatch2Template 
5. drag an drop a input from an ops (eg Phase of Sine ops) upon SubPatchInput nothing happen (a light freezing)
6. idem for SubPatchOutput impossible to create an output.

**Platform**
 - Mac Intel 3,1 GHz Intel Core i5 double cœur
 - Mac OS 13.6.7 (22G720)
 - version:cables standalone 0.2.0 / node: 20.13.1 / npm: 10.5.2

https://github.com/user-attachments/assets/7c2b20f3-56ff-4ff9-a385-901ef2737c96

![step 3](https://github.com/user-attachments/assets/e7dce9af-2484-4bbd-bef8-89b06dad1c99)
![step 4](https://github.com/user-attachments/assets/b1f2c4c3-b133-4b39-825a-72f7c5eb6cc8)
![step 5](https://github.com/user-attachments/assets/288620b6-ef9e-4b23-8c25-bec730bebd53)

**Comment by steam0r** [comment]
standalone hangs/crashes when creating subpatches

**Comment by nippotam** [comment]
Thanks 
When it will be released ?
