### ISSUE TITLE
Cannot create new files / drag and drop files from computer to editor Patch Files

### ISSUE THREAD

**Issue by kikohs** [cables-gl/cables_electron#139]
I was trying to create a new empty file or drag and drop but I get an error in the console.
Cables. 0.2.1 windows

**Comment by steam0r** [comment]
can you eleborate a bit or show/paste the error you get? how do you "create a new empty file", is the "drag and drop" also an empty file?

**Comment by kikohs** [comment]
Here is the workflow.
https://github.com/user-attachments/assets/898f071f-9778-44d5-b7b1-6705ad8cc206
