### ISSUE TITLE
Cannot install some npm packages with prebuilt binaries (windows)

### ISSUE THREAD

**Issue by kikohs** [cables-gl/cables_electron#145]
I'm continuing my exploration of the standalone release, unfortunately I couldn't install any of the following packages:

PGlite (postgres lite)
`@electric-sql/pglite`

LanceDB (vector database)
`@lancedb/lancedb`

SQLite with vector extension
`sqlite-vec`

They all rely on prebuilt binaries, and they don't match the electron version build if any. I tried to manually copy the right binary but on patch reload it's deleted.

Making op to store things in a local DB could be a great addition to the standalone release.

Thank you very much

**Comment by steam0r** [comment]
sooo...

cables standalone will now not delete previous node_modules if one build errors, `npm install` does though...

they seem to think thats the [right](https://github.com/npm/npm/issues/19450) [behaviour](https://github.com/npm/npm/issues/16853). anyhow:

`sqlite-vec`: comes with a precompiled binary that is compiled for the wrong nodevesion, cables standalone will show this in the console in the next release and a `npm install better-sqlite3` and `npx "@electron/rebuild" -v 31.7.3` fixes this...if you have nodejs installed on your machine, that is

`@lancedb/lancedb`: has a peer depedency of `apache-arrow` that needs to be resolved externally by doing `npm install apache-arrow` in the op directory

`@electric-sql/pglite`: crashes everything for unknown reasons....

next release will have more npms working, and better guidance if things do not work. that being said, all of these are more "backend" npms and these type of dependencies might need to be repackaged or have their binaries rebuilt...which cables will try to guide you through, now
