### ISSUE TITLE
do not link to docs if they don't (can't?) exist

### ISSUE THREAD

**Issue by pandrr** [cables-gl/cables_electron#181]
<img width="511" alt="Screenshot 2024-08-23 at 15 13 25" src="https://github.com/user-attachments/assets/48cc1ce9-5188-4efb-b10b-ad5ac3fc87d0">
<img width="373" alt="Screenshot 2024-08-23 at 15 13 13" src="https://github.com/user-attachments/assets/7cbe880e-4250-4785-a40d-c57dcf82016b">

**Comment by steam0r** [comment]
- also hide "op directory" if in "asar"
