### ISSUE TITLE
Special characters issue

### ISSUE THREAD

**Issue by 60-hz** [cables-gl/cables_electron#201]
**Describe the bug**
Spécial charcaters like accent (éàè...) are not working in comment and probably other text fields

<img width="507" alt="Capture d’écran 2024-09-04 à 16 16 00" src="https://github.com/user-attachments/assets/b1744aa0-b5f2-42e7-af08-ceb4132cf79b">

**Platform**
Mac Os Sonoma 14.3.1 (23D60)

**Comment by steam0r** [comment]
import font from "../glpatch/sdf_font.json";
