### ISSUE TITLE
Op namespace cannot be empty or only 'Ops'

### ISSUE THREAD

**Issue by 60-hz** [cables-gl/cables_electron#202]
Impossible to code new Op:
<img width="599" alt="Capture d’écran 2024-09-04 à 17 24 58" src="https://github.com/user-attachments/assets/f3a709e5-a0a8-4667-bb6d-9b1942f95829">

**How To Reproduce**
1. Open a Patch with a path set
2. Click on "Code New Op"
3.  Error

**Platform**
- MacOs Sonoma 14.3.1 (23D60)

**Comment by steam0r** [comment]
You need to name your op something like Op.MyNamespace.MyOp "cannot be empty or only `Ops.`"
the dropdown needs better suggestions, this is for sure

**Comment by 60-hz** [comment]
Oh, yes, got it!

**Comment by steam0r** [comment]
next version will have "Ops.Standalone." as a default namespace
