### ISSUE TITLE
OscSend: can't find module

### ISSUE THREAD

**Issue by stefanodalessio** [cables-gl/cables_electron#220]
MacOS arm64.
create an OscSend leads to: [Error] Cannot find module
<img width="1292" alt="Screenshot 2024-09-25 at 13 31 23" src="https://github.com/user-attachments/assets/b6411fd2-d30f-49ff-8db1-ade09bb66fda">

**Comment by steam0r** [comment]
will be fixed in next release, as a workaround you can clone the op and add "osc" as a npm package in "manage op" tab
