### ISSUE TITLE
Internet Disconnected Error

### ISSUE THREAD

**Issue by bejucoo** [cables-gl/cables_electron#223]
**Describe the bug**
My computer disconnected from internet a couple of minutes and got an error message: 

**How To Reproduce**
1. Open Editor
2. Disconnect from internet (?)

**Platform**
- Standalone 0.3.2
- OS: EndeavourOS Linux x86_64, 6.6.56-1-lts
- GPU: NVIDIA GeForce RTX 3050 Ti Mobile

**Logs**

```
cables_electron encountered an error
Error: net::ERR_INTERNET_DISCONNECTED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:115199)
    at SimpleURLLoaderWrapper.emit (node:events:519:28)

```

**Comment by steam0r** [comment]
are you using any httprequests or websockets or anything? does this happen in an empty patch?

**Comment by bejucoo** [comment]
No, no httprequests or websockets. It was a simple patch (mainloop + transform + cube). The one i was using to test the MediaRecorder problem.

**Comment by steam0r** [comment]
thanks, this is fixed in the next version
