### ISSUE TITLE
Popout Canvas closes cables entirely

### ISSUE THREAD

**Issue by bejucoo** [cables-gl/cables_electron#224]
**Describe the bug**
The editor starts with the Popout Canvas 'opened'. When I click on the popout button it opens the canvas again. When I click again on the popout button, the editor closes completely.

**How To Reproduce**
I'm not sure about this part. The editor was working fine but I closed the editor when a patch was running with the popout canvas. After that it began to behave this way.

**Platform**
- Standalone 0.3.2
- OS: EndeavourOS Linux x86_64, 6.6.56-1-lts
- GPU: NVIDIA GeForce RTX 3050 Ti Mobile

https://github.com/user-attachments/assets/e103af40-bc17-47a0-8a55-4707f9db7f16

**Comment by steam0r** [comment]
remove orange outline via css
