### ISSUE TITLE
SideBar not showed at right side

### ISSUE THREAD

**Issue by 60-hz** [cables-gl/cables_electron#230]
**Describe the bug**
If user check "Side" mode with sidebar Op, the right bar is not displayed in the canvas zone.
But it is when the canvas is pop out.

**Platform**
- Windows 11, standalone version 0.48

**Comment by pandrr** [comment]
works fine for me, can you make a video?

**Comment by 60-hz** [comment]
Sorry, it works now... lt was certainly a bad resolution on my screen. Closing!
