### ISSUE TITLE
load file from assets in standalone

### ISSUE THREAD

**Issue by wirmachenbunt** [cables-gl/cables_electron#51]
![image](https://github.com/cables-gl/cables_electron/assets/1138673/0e8cacf0-d0af-4acc-9c8e-786b356f78de)

**Comment by pandrr** [comment]
this should not be there, drop a file on the patchfield to load an asset

**Comment by wirmachenbunt** [comment]
> this should not be there, drop a file on the patchfield to load an asset

![image](https://github.com/cables-gl/cables_electron/assets/1138673/9589dfb7-8f0a-4762-a8fd-1a15499173dc)
this results always in something like this. how can i upload things to the assets folder ?

**Comment by steam0r** [comment]
for the standalone (for now) there will be no "asset folder" as there is on cables.gl, you simply access files on your local machine. these will be listed in file manager, eventually.

does the texture above work for you if you connect it somewhere? title is weird though....

**Comment by steam0r** [comment]
@wirmachenbunt how did you manage to get into the state of the first screenshot at all, do you remember?

**Comment by wirmachenbunt** [comment]
when i created the first cables project, it created the assets folder with it. looked like the stuff is supposed to be in there. hence i put the textures in the folder, accessed them via the UI in cables - > error

**Comment by steam0r** [comment]
okay, cool, thanks!
