### ISSUE TITLE
trying to open a popout canvas on the cables standalone 

### ISSUE THREAD

**Issue by VoidBoid** [cables-gl/cables_electron#56]
when i try to open a popout canvas on cables standalone i get this pop up (see pic)
i am on windows 10.
![IMG_20240514_101053](https://github.com/cables-gl/cables_electron/assets/94849610/9c97ef5b-054b-4812-afdf-fef23e7827df)

(sorry for the pic quality, the pop up didn't register on a screenshot)

**Comment by steam0r** [comment]
the iconbar is wrongly named and actually does "maximize canvas", cmd-p has a command to turn the window fullscreen, which (now) works as expected and removes the menu
