### ISSUE TITLE
Patch is empty while it is not

### ISSUE THREAD

**Issue by wirmachenbunt** [cables-gl/cables_electron#60]
![image](https://github.com/cables-gl/cables_electron/assets/1138673/4a903bea-8a3e-437a-aa6a-405736c11dba)

after starting the editor again, the patch is shown empty while it is probably not because another mainloop is complaining

[myfirstlocalproject.zip](https://github.com/cables-gl/cables_electron/files/15308267/myfirstlocalproject.zip)

**Comment by steam0r** [comment]
your zipfile contains a project with exactly one MainLoop, did you somehow scroll/move/pan away?
