### ISSUE TITLE
Webcam access under MacOS

### ISSUE THREAD

**Issue by 60-hz** [cables-gl/cables_electron#88]
When using the WebcamTexture Op under MacOS, the camera autorisation request is not sent, cables.gl is not in the software list in the preferences panel. Therefore, couldn't access to camera.

<img width="809" alt="Capture d’écran 2024-06-05 à 00 50 24" src="https://github.com/cables-gl/cables_electron/assets/5449719/1dd8e772-12e6-41a4-88ad-d71ac3eab507">

Tested under MacOS Sonoma 14.3.1 (23D60)

**Comment by pandrr** [comment]
not a bug, you did not allow it or it needs a user interaction

**Comment by 60-hz** [comment]
I tried with PlayButton and checked in Software autorisation for Camera...  It looks like cables app did not asked for autorisation.

Also, I have only "Default" in source list in the app.
<img width="417" alt="Capture d’écran 2024-06-05 à 12 02 49" src="https://github.com/cables-gl/cables_electron/assets/5449719/4578b69f-fe87-4404-baea-61e735b2b5e6">


In the online version of cables I have more choices, so it looks like the camera is not detected at all.

<img width="406" alt="Capture d’écran 2024-06-05 à 12 06 30" src="https://github.com/cables-gl/cables_electron/assets/5449719/f50d23ff-6aad-45de-b136-9868de9a2837">

**Comment by steam0r** [comment]
thanks for reporting, this is fixed in current dev version and will be in the next version, cables will now also show up in system preferences for permissions
