### ISSUE TITLE
Running NPM install before creating an OP fails

### ISSUE THREAD

**Issue by Zetaphor** [cables-gl/cables_electron#90]
## Environment

Running 0.0.5 AppImage on NixOS 24.05-stable with KDE Wayland

## Reproduction steps:

1. Create a new patch, add a Main Loop, save the patch
2. `npm install` a dependency to the patches root folder (ex: `path`)
3. CTRL-P in the patch and execute the NPM install command
4. NPM install fails to complete and throws a console error:

![image](https://github.com/cables-gl/cables_electron/assets/3112763/fd310dee-af81-499b-a529-144291c2a42f)

> node:electron/js2c/renderer_init:2 Uncaught (in promise) Error: Error invoking remote method 'talkerMessage': Error: ENOENT: no such file or directory, scandir '/home/zetaphor/Code/cables-patches/test/ops/'
    at IpcRenderer.invoke (node:electron/js2c/renderer_init:2:6995)
invoke @ node:electron/js2c/renderer_init:2
Promise.then (async)
s.runNpm @ cmd_electron.js:21
CMD.exec @ cablesui.js:36352
onResultClick @ cablesui.js:8396
onclick @ index.html:1
CommandPallete.keyDown @ cablesui.js:8310

No visual error is given, only the console output.

## Expected Behavior:

The npm packages should be installed to the patch, or there should be visual feedback to inform the user to first create a patch that uses the an NPM dependency.

**Comment by steam0r** [comment]
thanks for the report, this is fixed in the current dev build and will be in the next version

**Comment by Zetaphor** [comment]
I'm still seeing this issue in 0.0.6

**Comment by steam0r** [comment]
this should now just show "nothing to install"

**Comment by Zetaphor** [comment]
Confirmed fixed in v0.0.8

![image](https://github.com/cables-gl/cables_electron/assets/3112763/897be71e-36bc-49d8-a011-f9273007fd76)
