### ISSUE TITLE
Feature Request: Open OP in external editor

### ISSUE THREAD

**Issue by Zetaphor** [cables-gl/cables_electron#93]
Now that external editor support is enabled for ops, it would be great to have a button in the OP display and/or op editor display to open the `.js` file in an external editor. This would presumably take the form of a cables standalone setting that allows the user to enter the command to execute to trigger the file open, ex: `code %s` to open with VSCode/VSCodium.

**Comment by steam0r** [comment]
we have these buttons all over the place for local files:

![Bildschirmfoto 2024-06-12 um 19 03 07](https://github.com/cables-gl/cables_electron/assets/151271/656b0fbe-780c-4d36-bf98-0ba653ae107e)

i think it makes more sense to open the finder/explorer/filemanager and then click on the .js file to let the operating system handle file-associations.
