### ISSUE TITLE
Saving an OP loads it twice

### ISSUE THREAD

**Issue by Zetaphor** [cables-gl/cables_electron#94]
## Environment

Running 0.0.5 AppImage on NixOS 24.05-stable with KDE Wayland

## Reproduction steps:

1. Create a new patch, add a Main Loop, save the patch
2. Create a new op, add some debug logging
3. Save the op, the op is reloaded twice

This is creating an issue with my attempt to implement a set of Websocket server OPs, as the port is allocated on the first load, and then the OP is reloaded before the previous object and its port have been deallocated, resulting in the latest instance of the node import to fail to initialize.

https://github.com/cables-gl/cables_electron/assets/3112763/d2889bcc-bd00-4b8a-b4c5-b0b226f93814

## Expected Behavior:

An OP should only reload once when saved. I can work around this now by requiring a trigger to allocate the port, but this could present other issues as we start exploring API's with side effects.

**Comment by Zetaphor** [comment]
An extra observation, this only occurs when the node uses `op.require`

**Comment by steam0r** [comment]
this should be fine in 0.0.8

**Comment by Zetaphor** [comment]
Confirmed, this is resolved in 0.0.8
